name: action2sound
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - x264=1!157.20191217
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==23.2.0
      - audioread==3.0.1
      - av==11.0.0
      - blessed==1.20.0
      - braceexpand==0.1.7
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - decorator==4.4.2
      - decord==0.6.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - encodec==0.1.1
      - ffmpeg-python==0.2.0
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - frechet-audio-distance==0.2.0
      - fsspec==2023.12.2
      - ftfy==6.1.3
      - future==0.18.3
      - gammatone==1.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - grpcio==1.60.0
      - h5py==3.10.0
      - huggingface-hub==0.20.3
      - humanize==4.9.0
      - idna==3.6
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - keras==2.13.1
      - kiwisolver==1.4.5
      - laion-clap==1.1.5
      - libclang==16.0.6
      - librosa==0.8.0
      - llvmlite==0.42.0
      - markdown==3.5.2
      - markupsafe==2.1.4
      - matplotlib==3.8.2
      - ml-dtypes==0.2.0
      - mock==5.1.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - musdb==0.4.2
      - museval==0.4.1
      - networkx==3.2.1
      - noisereduce==3.0.0
      - nose==1.3.7
      - numba==0.59.0
      - numpy==1.23.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.2.0
      - pesq==0.0.4
      - pillow==10.2.0
      - platformdirs==4.2.0
      - pooch==1.8.0
      - proglog==0.1.10
      - progressbar==2.5
      - protobuf==3.20.3
      - psutil==5.9.8
      - pyaml==23.12.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydeprecate==0.3.1
      - pyparsing==3.1.1
      - pypesq==1.2.4
      - pystoi==0.4.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.2.10
      - pytz==2023.4
      - pyyaml==6.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rpds-py==0.17.1
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-learn==1.4.0
      - scipy==1.10.1
      - sentencepiece==0.1.99
      - sentry-sdk==1.40.4
      - setproctitle==1.3.3
      - simplejson==3.19.2
      - six==1.16.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - stempeg==0.2.3
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0.post1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.35.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - timm==0.4.5
      - tokenizers==0.13.3
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchlibrosa==0.0.2
      - torchmetrics==0.2.0
      - torchvision==0.17.0
      - tqdm==4.66.1
      - transformers==4.30.2
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2023.4
      - urllib3==2.2.0
      - wandb==0.16.3
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - werkzeug==3.0.1
      - wget==3.2
      - wrapt==1.14.1